global_costmap:
  global_frame: map  #地图坐标系
  robot_base_frame: base_footprint
  update_frequency: 5.0
  publish_frequency: 10.0
  static_map: true
 
  inflation_radius: 1.0
  transform_tolerance: 0.5
  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}