scan_filter_chain:
- name: box_filter
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: livox_frame
    max_x: 0.8
    max_y: 0.8
    max_z: 1.0
    min_x: -0.8
    min_y: -0.8
    min_z: -0.8
    invert: false
