# local_costmap:
#   global_frame: map
#   robot_base_frame: base_footprint
#   update_frequency: 5.0
#   publish_frequency: 2.0
#   static_map: false
#   rolling_window: true
#   width: 3.0
#   height: 3.5
#   resolution: 0.05
#   transform_tolerance: 0.5
  
  # plugins:
  #  - {name: static_layer,        type: "costmap_2d::StaticLayer"}
  #  - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}

local_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  #robot_base_frame: robot/base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false #不需要静态 地图，可以提升导航效果
  rolling_window: true #是否使用动态窗口，默认为false，在静态的全局地图中，地图不会变化
  width: 5.5 # 局部地图宽度 单位是 m
  height: 5.5 # 局部地图高度 单位是 m
  resolution: 0.1
  transform_tolerance: 0.5 # 局部地图分辨率 单位是 m，一般与静态地图分辨率保持一致
  
  plugins:
   - {name: static_layer,        type: "costmap_2d::StaticLayer"}
   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}